baseURL = 'https://lzwcc.github.io/'
languageCode = 'zh-cn'
title = "LZWcc's Blog"
theme = 'DoIt'

# 添加更多配置
[params]
  # 主页信息
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      title = "LZWcc's Blog"
      subtitle = "Student."
      avatarURL = "/images/avatar.jpg"
      typeit = true
      
  # 页脚信息
  [params.footer]
    enable = true
    copyright = true
    author = true
    since = 2023

  # 菜单配置
  [menu]
    [[menu.main]]
      identifier = "posts"
      name = "文章"
      url = "/posts/"
      weight = 1
    [[menu.main]]
      identifier = "categories"
      name = "分类"
      url = "/categories/"
      weight = 2
    [[menu.main]]
      identifier = "tags"
      name = "标签"
      url = "/tags/"
      weight = 3
    [[menu.main]]
      identifier = "about"
      name = "关于"
      url = "/about/"
      weight = 4