baseURL = 'https://lzwcc.github.io/'
defaultContentLanguage = "zh-cn"
languageCode = 'zh-CN'
title = "LZWcc's Blog"
theme = 'DoIt'

# 添加更多配置
[params]
  # DoIt 主题版本
  version = "0.2.X"
  math = true

  [params.page.math]
    enable = true
    # 块级公式分隔符
    blockLeftDelimiter = "$$"
    blockRightDelimiter = "$$"
    # 行内公式分隔符
    inlineLeftDelimiter = "$"
    inlineRightDelimiter = "$"
    # 其他选项
    copyTex = true
    mhchem = true
  [params.author]
  name = "LZWcc"
  email = "l1274645232@gmail.com"
  link = "https://lzwcc.github.io"
  
  # 主页信息
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      title = "LZWcc's Blog"
      subtitle = "Student."
      avatarURL = "/images/avatar.jpg"
      typeit = true
      
  # 页脚信息
  [params.footer]
    enable = true
    copyright = true
    author = true
    since = 2023

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "文章"
    url = "/posts/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "关于"
    url = "/about/"
    title = ""
    weight = 4

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置
  [markup.highlight]
    # false 是必要的设置
    noClasses = false
  